name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Add branch to env
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Log in to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=jirsh/ngx_modsec_brotli:${{ env.BRANCH }}
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jirsh/ngx_modsec_brotli:${{ env.BRANCH }}
            jirsh/ngx_modsec_brotli:latest
